# ==============================================================================
# Pre-commit framework configuration
# See https://pre-commit.com for more information
# ==============================================================================
repos:
  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v8.17.1
    hooks:
      - id: cspell
        name: 'CSpell: Enforce Spelling Compliance'
