[build-system]
requires = ["scikit-build-core", "pybind11", "numpy"]
build-backend = "scikit_build_core.build"

[project]
name = "pyrfl"
version = "0.1.0"
description = "Random Fuzzy Library (RFL) - MCMC simulations of Finite Random Non-commutative geometries"

authors = [{ name = "Paul Druce" }, { name = "Mauro D'Arcangelo" }]
requires-python = ">=3.8"
dependencies = [
    "numpy>=1.20"
]

[project.optional-dependencies]
test = ["pytest"]
dev = ["jupyter", "nbformat"]

[tool.scikit-build]
cmake.source-dir = "."

[tool.scikit-build.cmake.define]
CCACHE_PROGRAM = "OFF"

[tool.cibuildwheel]
build = "cp38-* cp39-* cp310-* cp311-* cp312-* cp313-*"
skip = "pp* *-musllinux* *-win32 *i686"
test-requires = ["pytest>=7.0", "numpy"]
test-command = "pytest {project}/src/RFL/python_bindings/tests"

[tool.cibuildwheel.linux]
manylinux-x86_64-image = "manylinux_2_28"
manylinux-aarch64-image = "manylinux_2_28"
before-all = [
    "dnf install -y epel-release || yum install -y epel-release",
    "dnf install -y openblas-devel lapack-devel gsl-devel armadillo-devel arpack-devel SuperLU-devel || yum install -y openblas-devel lapack-devel gsl-devel armadillo-devel"
]
repair-wheel-command = "auditwheel repair -w {dest_dir} {wheel}"

[tool.cibuildwheel.macos]
before-all = "brew install openblas lapack gsl armadillo arpack superlu pkg-config"
repair-wheel-command = "delocate-wheel --require-archs {delocate_archs} -w {dest_dir} -v {wheel}"
