# plugin_repo(
#     name = "cc",
#     owner = "please-build",
#     plugin = "cc-rules",
#     revision = "v0.4.0",
# )

plugin_repo(
    name = "cc",
    owner = "pauldruce",
    plugin = "please-cc-rules",
    revision = "da5c6c3c27eaf94ca3eaf0c9619fd907115d38b4",
)