cc_binary(
    name = "hmc_tuning",
    srcs = ["hmc_tuning.cpp"],
    deps = ["//src/RFL/legacy:rfl"],
)

cc_binary(
    name = "mauro_thesis_mmc",
    srcs = ["mauro_thesis_mmc.cpp"],
    deps = ["//src/RFL/legacy:rfl"],
)
