cc_binary(
    name = "mauro_mmc_example",
    srcs = ["mauro_thesis_example.cpp"],
    deps = ["//src/RFL/old_RFL:rfl"],
)

cc_binary(
    name = "mauro_hmc_example",
    srcs = ["mauro_hmc_example.cpp"],
    deps = ["//src/RFL/old_RFL:rfl"],
)