name: C++ Linter

on:
  pull_request:
    paths:
      - 'src/RFL/**'
      - 'playground/**'
      - '.clang-format'
      - '.github/workflows/linter.yml'
  push:
    branches: [ main ]
    paths:
      - 'src/RFL/**'
      - 'playground/**'
      - '.clang-format'
      - '.github/workflows/linter.yml'
  workflow_dispatch:

jobs:
  clang-format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - "src/RFL"
          - "playground"
    steps:
      - uses: actions/checkout@v7

      - name: Run clang-format style check for ${{ matrix.path }}.
        uses: jidicula/clang-format-action@v4.18.0
        with:
          clang-format-version: "16"
          check-path: ${{ matrix.path }}
